### ISSUE TITLE
Some icons not converting

### ISSUE THREAD

**Issue by Smartkin** [MightyDuke/ico2gltf#1]
Some icons like in Crash Twinsanity are presented as an uncompressed texture. Resulting in a crash of the script since a compressed texture is always expected.

Reproduction:
Run the script on Crash Twinsanity's ICO.
![image](https://user-images.githubusercontent.com/23398959/94360559-da36bb80-00b6-11eb-89b4-6dc8c647a89c.png)

[Crash.zip](https://github.com/MightyDuke/ico2gltf/files/5287984/Crash.zip)

**Comment by MightyDuke** [comment]
Thank you for reporting this, it should be fixed now.
